import type { ContentCategory } from "../content/contentApi";

export const appText = {
  ptBR: {
    language: {
      label: "Idioma",
      toggleLabel: "Trocar idioma",
      current: "BR PT",
      next: "US EN",
    },
    categories: {
      NULL: "NULL",
      "Para Voce": "Para Voce",
      Animes: "Animes",
      Mangas: "Mangas",
      Filmes: "Filmes",
      Series: "Series",
      Livros: "Livros",
      Jogos: "Jogos",
    } satisfies Record<ContentCategory, string>,
    navbar: {
      ariaLabel: "Categorias",
      profileAlt: "Foto de perfil",
      profileTitle: "Perfil",
      openMenu: "Abrir menu",
      closeMenu: "Fechar menu",
    },
    auth: {
      requiredFields: "Preencha todos os campos.",
      invalidEmail: "Informe um email valido.",
      shortPassword: "A senha deve ter no minimo {min} caracteres.",
      passwordMismatch: "Senha e confirmar senha precisam ser iguais.",
      signingUp: "Criando cadastro...",
      signingIn: "Entrando...",
      accountCreated: "Cadastro criado. O codigo foi enviado para seu email.",
      loginSuccess: "Login realizado com sucesso.",
      authError: "Nao foi possivel autenticar agora.",
      signingUpButton: "Cadastrando...",
      signingInButton: "Entrando...",
      enter: "Entrar",
      register: "Cadastrar",
      guestMode: "Modo convidado",
    },
    verifyEmail: {
      title: "Verificar email",
      description: "Digite o codigo enviado para seu email.",
      emailLabel: "E-mail",
      emailPlaceholder: "voce@exemplo.com",
      codeLabel: "Codigo de verificacao",
      codePlaceholder: "Digite o codigo",
      required: "Informe o email e o codigo de verificacao.",
      checking: "Verificando codigo...",
      success: "Email verificado com sucesso. Voce ja pode fazer login.",
      error: "Nao foi possivel verificar o email agora.",
      checkingButton: "Verificando...",
      submit: "Verificar",
      backToLogin: "Voltar para login",
    },
    main: {
      currentPage: "Pagina atual",
      page: "Pagina",
      searchPlaceholder: "Buscar em {category}",
      searchButton: "Pesquisar",
      clearButton: "Limpar",
      emptyResults: "Nenhum conteudo encontrado.",
      favoritesLoadError: "Sessao expirada ou erro ao carregar favoritos.",
      addFavoriteLogin: "Faca login para adicionar favoritos.",
      invalidFavoriteCategory: "Esta categoria nao pode ser favoritada.",
      favoriteAdded: "Favorito adicionado.",
      favoriteAddError: "Erro ao adicionar favorito.",
      categoryLoadError: "Nao foi possivel carregar esta categoria agora.",
      noImage: "Sem imagem",
      typeLabel: "Tipo",
      ratingLabel: "Nota",
      yearLabel: "Ano",
      noDescription: "Sem descricao disponivel.",
      favorited: "Favoritado",
      addFavorite: "Adicionar aos favoritos",
      previous: "Anterior",
      next: "Proxima",
      addFavoriteTitle: "Adicionar favorito",
      close: "Fechar",
      statusLabel: "Status",
      startLabel: "Inicio",
      endLabel: "Termino",
      commentLabel: "Comentario",
      cancel: "Cancelar",
      adding: "Adicionando...",
      add: "Adicionar",
    },
    profile: {
      title: "Perfil",
      publicTitle: "Perfil publico",
      userFallback: "Usuario",
      accountData: "Dados da conta",
      publicData: "Dados publicos",
      nameLabel: "Nome",
      saveName: "Salvar nome",
      editName: "Editar nome",
      logout: "Sair",
      favorites: "Favoritos",
      loadingFavorites: "Carregando favoritos...",
      favoritesError: "Erro ao carregar favoritos.",
      noFavorites: "Nenhum favorito adicionado ainda.",
      publicNoFavorites: "Este perfil ainda nao tem favoritos.",
      noFavoritesInStatus: "Sem favoritos em {status}.",
      favoriteUpdated: "Favorito atualizado.",
      favoriteRemoved: "Favorito removido.",
      updateFavoriteError: "Erro ao atualizar favorito.",
      removeFavoriteError: "Erro ao remover favorito.",
      nameTooShort: "Informe um nome com pelo menos 2 caracteres.",
      sessionExpired: "Sessao expirada. Faca login novamente.",
      nameUpdated: "Nome atualizado com sucesso.",
      nameUpdateError: "Nao foi possivel atualizar o nome agora.",
      loadingProfile: "Carregando perfil...",
      userNotFound: "Usuario nao encontrado.",
      fetchProfileError: "Erro ao buscar perfil.",
      back: "Voltar",
      noImage: "Sem imagem",
      statusLabel: "Status",
      typeLabel: "Tipo",
      ratingLabel: "Nota",
      periodLabel: "Periodo",
      noDates: "Sem datas",
      noStart: "Sem inicio",
      noEnd: "Sem termino",
      noComment: "Sem comentario",
      close: "Fechar",
      startLabel: "Inicio",
      endLabel: "Termino",
      commentLabel: "Comentario",
      save: "Salvar",
      remove: "Remover",
      searchUsersPlaceholder: "Buscar usuarios",
      searchUsersLabel: "Buscar usuarios",
      usersLoading: "Carregando usuarios...",
      usersError: "Erro ao buscar usuarios.",
      noUsersFound: "Nenhum usuario encontrado.",
      emptyUserSearch: "Digite para buscar usuarios.",
      status: {
        watch: "Quero assistir",
        watching: "Assistindo",
        watched: "Assistidos",
        gameWatch: "Quero jogar",
        gameWatching: "Jogando",
        gameWatched: "Jogados",
        readWatch: "Quero ler",
        readWatching: "Lendo",
        readWatched: "Lidos",
      },
      moment: {
        episode: "Episodio",
        chapter: "Capitulo",
      },
      contentTypes: {
        anime: "Anime",
        movie: "Filme",
        series: "Serie",
        manga: "Manga",
        book: "Livro",
        game: "Jogo",
      },
    },
  },
  en: {
    language: {
      label: "Language",
      toggleLabel: "Change language",
      current: "US EN",
      next: "BR PT",
    },
    categories: {
      NULL: "NULL",
      "Para Voce": "For You",
      Animes: "Anime",
      Mangas: "Manga",
      Filmes: "Movies",
      Series: "Series",
      Livros: "Books",
      Jogos: "Games",
    } satisfies Record<ContentCategory, string>,
    navbar: {
      ariaLabel: "Categories",
      profileAlt: "Profile picture",
      profileTitle: "Profile",
      openMenu: "Open menu",
      closeMenu: "Close menu",
    },
    auth: {
      requiredFields: "Fill in all fields.",
      invalidEmail: "Enter a valid email.",
      shortPassword: "Password must be at least {min} characters.",
      passwordMismatch: "Password and confirmation must match.",
      signingUp: "Creating account...",
      signingIn: "Signing in...",
      accountCreated: "Account created. The code was sent to your email.",
      loginSuccess: "Signed in successfully.",
      authError: "Could not authenticate right now.",
      signingUpButton: "Signing up...",
      signingInButton: "Signing in...",
      enter: "Sign in",
      register: "Sign up",
      guestMode: "Guest mode",
    },
    verifyEmail: {
      title: "Verify email",
      description: "Enter the code sent to your email.",
      emailLabel: "Email",
      emailPlaceholder: "you@example.com",
      codeLabel: "Verification code",
      codePlaceholder: "Enter the code",
      required: "Enter the email and verification code.",
      checking: "Checking code...",
      success: "Email verified successfully. You can now sign in.",
      error: "Could not verify the email right now.",
      checkingButton: "Checking...",
      submit: "Verify",
      backToLogin: "Back to login",
    },
    main: {
      currentPage: "Current page",
      page: "Page",
      searchPlaceholder: "Search in {category}",
      searchButton: "Search",
      clearButton: "Clear",
      emptyResults: "No content found.",
      favoritesLoadError: "Session expired or favorites could not be loaded.",
      addFavoriteLogin: "Sign in to add favorites.",
      invalidFavoriteCategory: "This category cannot be favorited.",
      favoriteAdded: "Favorite added.",
      favoriteAddError: "Error adding favorite.",
      categoryLoadError: "Could not load this category right now.",
      noImage: "No image",
      typeLabel: "Type",
      ratingLabel: "Rating",
      yearLabel: "Year",
      noDescription: "No description available.",
      favorited: "Favorited",
      addFavorite: "Add to favorites",
      previous: "Previous",
      next: "Next",
      addFavoriteTitle: "Add favorite",
      close: "Close",
      statusLabel: "Status",
      startLabel: "Start",
      endLabel: "End",
      commentLabel: "Comment",
      cancel: "Cancel",
      adding: "Adding...",
      add: "Add",
    },
    profile: {
      title: "Profile",
      publicTitle: "Public profile",
      userFallback: "User",
      accountData: "Account data",
      publicData: "Public data",
      nameLabel: "Name",
      saveName: "Save name",
      editName: "Edit name",
      logout: "Exit",
      favorites: "Favorites",
      loadingFavorites: "Loading favorites...",
      favoritesError: "Error loading favorites.",
      noFavorites: "No favorites added yet.",
      publicNoFavorites: "This profile has no favorites yet.",
      noFavoritesInStatus: "No favorites in {status}.",
      favoriteUpdated: "Favorite updated.",
      favoriteRemoved: "Favorite removed.",
      updateFavoriteError: "Error updating favorite.",
      removeFavoriteError: "Error removing favorite.",
      nameTooShort: "Enter a name with at least 2 characters.",
      sessionExpired: "Session expired. Sign in again.",
      nameUpdated: "Name updated successfully.",
      nameUpdateError: "Could not update the name right now.",
      loadingProfile: "Loading profile...",
      userNotFound: "User not found.",
      fetchProfileError: "Error loading profile.",
      back: "Back",
      noImage: "No image",
      statusLabel: "Status",
      typeLabel: "Type",
      ratingLabel: "Rating",
      periodLabel: "Period",
      noDates: "No dates",
      noStart: "No start",
      noEnd: "No end",
      noComment: "No comment",
      close: "Close",
      startLabel: "Start",
      endLabel: "End",
      commentLabel: "Comment",
      save: "Save",
      remove: "Remove",
      searchUsersPlaceholder: "Search users",
      searchUsersLabel: "Search users",
      usersLoading: "Loading users...",
      usersError: "Error loading users.",
      noUsersFound: "No users found.",
      emptyUserSearch: "Type to search users.",
      status: {
        watch: "Want to watch",
        watching: "Watching",
        watched: "Watched",
        gameWatch: "Want to play",
        gameWatching: "Playing",
        gameWatched: "Played",
        readWatch: "Want to read",
        readWatching: "Reading",
        readWatched: "Read",
      },
      moment: {
        episode: "Episode",
        chapter: "Chapter",
      },
      contentTypes: {
        anime: "Anime",
        movie: "Movie",
        series: "Series",
        manga: "Manga",
        book: "Book",
        game: "Game",
      },
    },
  },
} as const;

export type AppLanguage = keyof typeof appText;
