export const englishLoginText = {
  languageLabel: "Language",
  languageName: "English",
  loginTitle: "Login",
  signUpTitle: "Create account",
  loginDescription: "Access your content list.",
  signUpDescription: "Create your account to start organizing your list.",
  nameLabel: "Name",
  namePlaceholder: "Your name",
  emailLabel: "Email",
  emailPlaceholder: "you@example.com",
  passwordLabel: "Password",
  passwordPlaceholder: "Enter your password",
  confirmPasswordLabel: "Confirm password",
  confirmPasswordPlaceholder: "Repeat your password",
  showPassword: "Show password",
  hidePassword: "Hide password",
  loginButton: "Enter",
  signUpButton: "Sign up",
  logoutButton: "Exit",
  switchToSignUp: "Need an account? Sign up",
  switchToLogin: "Already have an account? Login",
} as const;
