export const portugueseLoginText = {
  languageLabel: "Idioma",
  languageName: "Português",
  loginTitle: "Login",
  signUpTitle: "Cadastro",
  loginDescription: "Acesse sua lista de conteúdos.",
  signUpDescription: "Crie sua conta para começar a organizar sua lista.",
  nameLabel: "Nome",
  namePlaceholder: "Seu nome",
  emailLabel: "E-mail",
  emailPlaceholder: "voce@exemplo.com",
  passwordLabel: "Senha",
  passwordPlaceholder: "Digite sua senha",
  confirmPasswordLabel: "Confirmar senha",
  confirmPasswordPlaceholder: "Repita sua senha",
  showPassword: "Mostrar senha",
  hidePassword: "Ocultar senha",
  loginButton: "Entrar",
  signUpButton: "Cadastrar",
  logoutButton: "Sair",
  switchToSignUp: "Precisa de uma conta? Cadastre-se",
  switchToLogin: "Já tem uma conta? Entrar",
} as const;
